### PR TITLE
Update formatter.ts

### PR DESCRIPTION
**Pull request by runlevelsix**
Regex flags are being classified as comments in some cases, I think this will fix that issue.

### CODE REVIEW

**Comment by runlevelsix** [comment]
Thank you for merging this pull request. Will you be releasing this back into the VS Code Extensions Marketplace?

**Comment by xandeer** [comment]
Sorry, have you build it before? There are some wrong with your code. I try this plugin with Regex flags, and it's OK. Can you show me some incorrect cases?

**Comment by runlevelsix** [comment]
How do I enable the regex flag? I didn't see it in any of the configurable
places in VS Code.

**Comment by xandeer** [comment]
I don't know what you want. Here are some codes before using this plugin:
```javascript

const aaaa = 1
const asdfdf = 'asdfe'
const reg = /h(.*), /gi // Regex
```

And after:
```javascript

const aaaa   = 1
const asdfdf = 'asdfe'
const reg    = /h(.*),/gi // Regex
```

If there is something you want to know, please show me your codes.

**Pull request merged**
